# Generated by Django 4.1.9 on 2023-07-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('rank', '0001_initial'), ('rank', '0002_alter_scoringboard_channel')]

    initial = True

    dependencies = [
        ('ingeupdong', '0005_alter_channel_created_at_alter_channel_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ingeupdong.channel')),
            ],
            options={
                'db_table': 'scores_on_channel',
            },
        ),
    ]
