# Generated by Django 4.1.9 on 2023-07-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingeupdong', '0001_squashed_0005_alter_channel_created_at_alter_channel_handle_and_more'),
        ('rank', '0001_squashed_0002_alter_scoringboard_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreOnChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=30)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='ingeupdong.channel')),
            ],
            options={
                'db_table': 'score_on_channel',
            },
        ),
        migrations.DeleteModel(
            name='ScoringBoard',
        ),
    ]
