# Generated by Django 4.1.9 on 2023-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_scoreonchannel_delete_scoringboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreonchannel',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='scoreonchannel',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
