# Generated by Django 4.1.9 on 2023-07-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ingeupdong', '0001_initial'), ('ingeupdong', '0002_channel_create_at_video_create_at'), ('ingeupdong', '0003_rename_create_at_channel_created_at_and_more'), ('ingeupdong', '0004_alter_trendingboard_managers'), ('ingeupdong', '0005_alter_channel_created_at_alter_channel_handle_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='채널명', max_length=150)),
                ('handle', models.CharField(help_text='채널 핸들명', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='채널의 첫 크롤링 날짜')),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='RecordingBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_at', models.DateTimeField(auto_now=True, help_text='크롤링 날짜')),
            ],
            options={
                'db_table': 'recording',
                'ordering': ['record_at'],
                'get_latest_by': ['record_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='동영상 제목', max_length=120)),
                ('url', models.CharField(help_text='동영상 url', max_length=50, unique=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='ingeupdong.channel')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='영상의 첫 크롤링 날짜')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='TrendingBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='인급동 순위')),
                ('views', models.PositiveBigIntegerField(help_text='영상 조회수')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingeupdong.recordingboard')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='ingeupdong.video')),
            ],
            options={
                'db_table': 'trending',
                'ordering': ['record', 'rank'],
            },
        ),
    ]
