# Generated by Django 4.1.7 on 2023-05-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingeupdong', '0002_channel_create_at_video_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
