# Generated by Django 4.1.9 on 2023-07-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingeupdong', '0003_rename_create_at_channel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trendingboard',
            managers=[
            ],
        ),
    ]
