# Generated by Django 4.1.9 on 2023-07-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingeupdong', '0001_squashed_0005_alter_channel_created_at_alter_channel_handle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'get_latest_by': ['created_at']},
        ),
    ]
